### PR TITLE
Wip adjust route issue2

### LINKED ISSUE #2: Adjust Root to Redirect to ‘/reminders’
When the user visits the root of the application, they should be redirected to '/reminders' and should see a list of all reminders on the page. This means making a hopefully small adjustment to your router.js file.

**Hot Tip**: This will make your previous test fail (if you had it passing). Make the necessary changes in the test(s).

### PR DESCRIPTION
**Pull request by mlimberg**
@martensonbj @Tman22 

Closes #2
## Purpose

Redirects user immediately from root to the /reminders route and displays reminders from store 
[link to issue](https://github.com/turingschool-projects/1610-remember-5/issues/2)

## Approach

It solves issue 2

### Learning

After battling our own egos yesterday, we went back and read the docs, stopped listening to tay tay and just did our own thing (jk black bear)

### Test coverage 

Mostly just testing that things exist at the moment

### Merge Dependencies and Related Work

Built off of un-merged work from PR #1 

### Follow-up tasks

- Issue #3

### CODE REVIEW

File: tests/acceptance/reminder-list-test.js [hunk 1]
```diff
@@ -25,7 +25,7 @@ test('clicking on an individual item', function(assert) {
   click('.spec-reminder-item:first');
 
   andThen(function() {
-    assert.equal(currentURL(), '/1');
-    assert.equal(Ember.$('.spec-reminder-item:first').text().trim(), Ember.$('.spec-reminder-title').text().trim());
+    assert.equal(currentURL(), '/');
+    assert.equal(Ember.$('.spec-reminder-item').find('.spec-reminder-title').text().trim(), Ember.$('.spec-reminder-title').text().trim());
```
Comment (martensonbj) [inline tests/acceptance/reminder-list-test.js]: It looks like here you're testing that the title you find matches the title you just found...i'd rather see a count verification here.

**Review by martensonbj — CHANGES_REQUESTED** [review]
Based on the changes you made - the acceptance tests you have will be failing. Please make sure those are passing, make the reminders-list test change, and add some valid assertions in the remaining boilerplate tests or remove those files if you aren't using them.

File: app/templates/index.hbs [hunk 2]
```diff
@@ -0,0 +1 @@
+{{outlet}}
```
Comment (martensonbj) [inline app/templates/index.hbs:1]: Don't need this file - I'll merge this in but make sure it's gone by the next PR.

File: tests/unit/routes/reminders-test.js [hunk 3]
```diff
@@ -0,0 +1,11 @@
+import { moduleFor, test } from 'ember-qunit';
```
Comment (martensonbj) [inline tests/unit/routes/reminders-test.js:1]: Get rid of this file - we don't need to to test routes in these files

File: tests/unit/routes/index-test.js [hunk 4]
```diff
@@ -0,0 +1,11 @@
+import { moduleFor, test } from 'ember-qunit';
```
Comment (martensonbj) [inline tests/unit/routes/index-test.js:1]: Don't need route tests unless you're testing something unconventional

**Review by martensonbj — APPROVED** [review]
Merging this in but please remove the index.hbs file, and the route-test files.
