### PR TITLE
Display reminders on homepage Closes #1

### LINKED ISSUE #1: See All Reminders
When the user visits the root of the application (e.g. the "/" URL), they should see a list of all of the reminders on the page.

* Each reminder should have a class of .spec-reminder-item.

* There is a failing test set up in tests/acceptance/reminder-list-test.js.

**Hot Reminder**: If you put “Closes #1” (assuming the issue is marked #1) in the pull request, your commit, or anywhere in the body of your PR, it will automatically close this issue when it successfully merged into master.

### PR DESCRIPTION
**Pull request by sljohnson32**
@martensonbj @Tman22 

## Purpose

PR adds reminders component to display all reminders on homepage.
`https://github.com/turingschool-projects/1610-remember-5/issues/1`

## Approach

This PR creates a component to display reminders.

### Learning

Used Ember docs to walk through the Routes/Templates process.
`http://guides.emberjs.com/v2.11.0/tutorial/routes-and-templates/`

### Open Questions and Pre-Merge TODOs

Is the expectation here that we are pulling data from Mirage.  If so, can you provide some tips/hints on doing.

### Test coverage 

Used test provided in boilerplate and passing with 5 reminders on page.

### Merge Dependencies and Related Work

None.

### Follow-up tasks

- [Issue #2](https://github.com/turingschool-projects/1610-remember-5/issues/2)

### CODE REVIEW

File: app/router.js [hunk 1]
```diff
@@ -7,6 +7,9 @@ const Router = Ember.Router.extend({
 });
 
 Router.map(function() {
+  this.route('reminders', {
```
Comment (martensonbj) [inline app/router.js]: This can be on one line

File: app/routes/reminders.js [hunk 2]
```diff
@@ -0,0 +1,37 @@
+import Ember from 'ember';
+
+export default Ember.Route.extend({
+  model() {
```
Comment (martensonbj) [inline app/routes/reminders.js:4]: Mirage is generating your models behind the scenes. Look into how to grab records from the store instead of hard coding them in here.

File: tests/unit/routes/reminders-test.js [hunk 3]
```diff
@@ -0,0 +1,11 @@
+import { moduleFor, test } from 'ember-qunit';
```
Comment (martensonbj) [inline tests/unit/routes/reminders-test.js:1]: If you have a test file lets make sure there's a legit assertion not just the boilerplate code.

**Review by martensonbj — CHANGES_REQUESTED** [review]
Few small changes. Good start!

**Comment by sljohnson32** [comment]
@martensonbj @Tman22 We've made the adjustments requested and resubmitted.

**Review by martensonbj — APPROVED** [review]
I'll merge this in for now - but keep a closer eye on empty test files. You have a couple that still only have boilerplate code and in the future we won't merge a PR with boilerplate code and comments.
